# have to use visual studio 2017
# because without it vswhere is broken:
# https://github.com/Microsoft/vswhere/issues/87
# https://github.com/Microsoft/vswhere/issues/91
image: Visual Studio 2017
shallow_clone: true

install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python --version
  # need for parallel tests
  - pip install pypiwin32
  # need for Docbook tests
  - pip install lxml
  # dependency for D tests
  - choco install dmd
  # dependency for ldc tests
  - choco install ldc
  # depedency for swig tests
  - choco install swig
  # dependency for MSVS tests
  - choco install vswhere

  # dependency for clang tests
  - set PATH="C:\msys64";"C:\Program Files\LLVM\bin";%PATH%
  - clang++ -v
  - clang -v

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      BUILD_JOB_NUM: 1
    - PYTHON: "C:\\Python27"
      BUILD_JOB_NUM: 2
    - PYTHON: "C:\\Python27"
      BUILD_JOB_NUM: 3
    - PYTHON: "C:\\Python27"
      BUILD_JOB_NUM: 4

#    - PYTHON: "C:\\Python35"
#      BUILD_JOB_NUM: 1
#    - PYTHON: "C:\\Python35"
#      BUILD_JOB_NUM: 2
#    - PYTHON: "C:\\Python35"
#      BUILD_JOB_NUM: 3
#    - PYTHON: "C:\\Python35"
#      BUILD_JOB_NUM: 4
#
#    - PYTHON: "C:\\Python36"
#      BUILD_JOB_NUM: 1
#    - PYTHON: "C:\\Python36"
#      BUILD_JOB_NUM: 2
#    - PYTHON: "C:\\Python36"
#      BUILD_JOB_NUM: 3
#    - PYTHON: "C:\\Python36"
#      BUILD_JOB_NUM: 4
#
#    - PYTHON: "C:\\Python27-x64"
#      BUILD_JOB_NUM: 1
#    - PYTHON: "C:\\Python27-x64"
#      BUILD_JOB_NUM: 2
#    - PYTHON: "C:\\Python27-x64"
#      BUILD_JOB_NUM: 3
#    - PYTHON: "C:\\Python27-x64"
#      BUILD_JOB_NUM: 4
#
#    - PYTHON: "C:\\Python35-x64"
#      BUILD_JOB_NUM: 1
#    - PYTHON: "C:\\Python35-x64"
#      BUILD_JOB_NUM: 2
#    - PYTHON: "C:\\Python35-x64"
#      BUILD_JOB_NUM: 3
#    - PYTHON: "C:\\Python35-x64"
#      BUILD_JOB_NUM: 4
#      
#    - PYTHON: "C:\\Python36-x64"
#      BUILD_JOB_NUM: 1
#    - PYTHON: "C:\\Python36-x64"
#      BUILD_JOB_NUM: 2
#    - PYTHON: "C:\\Python36-x64"
#      BUILD_JOB_NUM: 3
#    - PYTHON: "C:\\Python36-x64"
#      BUILD_JOB_NUM: 4

build: off
build_script:
  # Have to do this in one line if I want the script in the appveyor file: 
  # https://stackoverflow.com/a/37647169
  - cmd: python runtest.py -l -a > all_tests.txt & powershell -Command "& {$TOTAL_BUILD_JOBS = 4; $Lines = (Get-Content all_tests.txt | Measure-Object -line).Lines; $start = ($Lines / $TOTAL_BUILD_JOBS) * ($Env:BUILD_JOB_NUM - 1); $end = ($Lines / $TOTAL_BUILD_JOBS) * $Env:BUILD_JOB_NUM; if($Env:BUILD_JOB_NUM -eq $TOTAL_BUILD_JOBS){ $end = $Lines }; if ( $start -eq 0 ){ $start = 1 }; get-content all_tests.txt | select -first ($end - $start) -skip ($start - 1) | Out-File -Encoding ASCII build_tests.txt}" & powershell -Command "& {Write-Host $Env:PATH; }" & python runtest.py -f build_tests.txt