image: Visual Studio 2017
shallow_clone: true

install:
  #set python version, and cygwin tools for clang tests
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;C:\\cygwin64\\bin;C:\\msys64;%PATH%"
  - python --version
  - pip install lxml
  - pip install pypiwin32
  - choco install dmd
  - choco install ldc
  - choco install swig
  - choco install vswhere

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      BUILD_JOB_NUM: 1
    

build: off
build_script:
  - cmd: python runtest.py test/Clang
  