#version: '3.0.1.{build}'

image: Visual Studio 2015

cache:
  - downloads -> appveyor.yml
  - '%LOCALAPPDATA%\pip\Cache'
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;C:\\cygwin64\\bin;C:\\msys64;%PATH%"

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      BUILD_JOB_NUM: 1

build: off

build_script:
  - cmd: |
      dir "C:/Program Files/Java"
      dir "C:/Program Files/Java/jdk1.6.0"
      dir "C:/Program Files/Java/jdk1.6.0/bin"
      dir "C:/Program Files/Java/jdk1.7.0"
      dir "C:/Program Files/Java/jdk1.7.0/bin"
      dir "C:/Program Files (x86)/Java"
      dir "C:/Program Files (x86)/Java/jdk1.6.0"
      dir "C:/Program Files (x86)/Java/jdk1.6.0/bin"
      dir "C:/Program Files (x86)/Java/jdk1.7.0"
      dir "C:/Program Files (x86)/Java/jdk1.7.0/bin"
