dist: trusty
language: python


# pypy is not passing, but allow failures for coverage stage to be reached
matrix:
  allow_failures:
    - python: pypy


jobs:
  include:
    - &test_job
      stage: Test
      script: 
      # WORKAROUND: attempt to retry JobTests.py if it fails and then continue if it passes, if it fails ten times
      # then it is a real failure not related to intermittent travis failures
        - n=0; while [[ $n -lt 200 ]]; do python runtest.py src/engine/SCons/JobTests.py; done;
      before_script: skip
      after_success: skip
      python: 2.7
      env: PYVER=27
      sudo: required

    - <<: *test_job
      python: 3.5
      env: PYVER=35
      sudo: required

    - <<: *test_job
      python: 3.6
      env: PYVER=36
      sudo: required

    - <<: *test_job
      python: pypy
      env: PYVER=pypy
      sudo: required


    
