dist: trusty
before_install:
  - sudo apt-get -y install clang python-pip python-dev build-essential libpcre3-dev autoconf automake libtool bison subversion git
  - sudo pip install lxml
  - wget https://github.com/swig/swig/archive/rel-3.0.12.tar.gz
  - tar xzf rel-3.0.12.tar.gz
  - cd swig-rel-3.0.12 && ./autogen.sh && ./configure --prefix=/usr && make && sudo make install && cd ..
  - sudo pip install coverage
  - sudo pip install coveralls
  - echo "import coverage" | sudo tee --append /usr/lib/python2.7/sitecustomize.py
  - echo "coverage.process_startup()" | sudo tee --append /usr/lib/python2.7/sitecustomize.py 

script: 
  - export COVERAGE_PROCESS_START=$PWD/.coveragerc
  - echo "[run]" >> .coveragerc
  - echo "source = $PWD/src" >> .coveragerc
  - echo "parallel = True" >> .coveragerc
  - coverage run --rcfile=$PWD/.coveragerc runtest.py -a || if [[ $? == 2 ]]; then exit 0; else exit 1; fi
  - coverage combine
  - coverage report
  - coveralls --rcfile=$PWD/.coveragerc
