
language: ruby
addons:
    apt:
      update: true

os:
  - osx

# run coverage first as its still useful to collect
stages:
  - Test

jobs:
  include:
    - &test_job
      stage: Test
      script: 
        - python runtest.py test/Repository/ShardLibrary.py
      before_script: skip
      after_success: skip
      
