dist: trusty
before_install:
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get install python3.5
matrix:
  include:
    - python: '3.5' # this is not strictly necessary
      env: PYTHONCOM=/usr/bin/python3.5
    - python: '2.7'
      env: PYTHONCOM=/usr/bin/python

script: 
  - $PYTHONCOM runtest.py src/engine/SCons/JobTests.py
