dist: trusty
before_install:
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get -y install python3.5 python3-pip python-virtualenv python-pip python-dev
  - sudo pip install lxml
  - sudo pip3 install lxml

matrix:
  include:
    - python: '3.5' # this is not strictly necessary
      env: PYTHONCOM=python3.5
    - python: '2.7'
      env: PYTHONCOM=python

script: 
  - /usr/bin/$PYTHONCOM src/script/scons.py
  - /usr/bin/$PYTHONCOM runtest.py src/test_setup.py
