
environment:
  matrix:
    - BUILD_JOB_NUM: 1
    - BUILD_JOB_NUM: 2
    - BUILD_JOB_NUM: 3
    - BUILD_JOB_NUM: 4
    - BUILD_JOB_NUM: 5
    - BUILD_JOB_NUM: 6
    - BUILD_JOB_NUM: 7
    - BUILD_JOB_NUM: 8

build: off
build_script:
  - ps: >-
      & ".\runtest.py" -myArgument "-l -a" | Out-File all_tests.txt
      $TOTAL_BUILD_JOBS = 8
      $Lines = (Get-Content all_tests.txt | Measure-Object -line).Lines
      $start = ($Lines / $TOTAL_BUILD_JOBS) * ($BUILD_JOB_NUM - 1)
      $end = ($Lines / $TOTAL_BUILD_JOBS) * $BUILD_JOB_NUM
      if($BUILD_JOB_NUM == $TOTAL_BUILD_JOBS){
        $end = $Lines
      }
      if ( $start == 0 ){
        $start = 1
      }
      get-content all_tests.txt | select -first $start -last $end  | Out-File build_tests.txt
  - ps: >-
      & ".\runtest.py" -myArgument "-f build_tests.txt"
      if( $lastexitcode == 2 ) { $lastexitcode = 0 }
  
