version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/python:3.8'
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: python --version