version: 2.1
jobs:
  test38:
    docker:
      - image: 'python:3.8'
    steps:
      - run: python --version
      - checkout
      - run: python runtest.py -a -j 2 -v -s || if [[ $? == 2 ]]; then true; else false; fi

  test37:
    docker:
      - image: 'python:3.7'
    steps:
      - run: python --version
      - checkout
      - run: python runtest.py -s --passed -a -j 2 -v || if [[ $? == 2 ]]; then true; else false; fi

workflows:
  version: 2.1
  test_all:
    jobs:
      - test37