version: 2.1

jobs:
  test:
    parameters:
      image:
        type: string

    docker:
      - image: << parameters.image >>

    steps:
      - run: python --version
      - checkout
      - run: python runtest.py --verbose=3  -f .circleci/base_docker_tests.txt -j 2 || if [[ $? == 2 ]]; then true; else false; fi

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              image: ['python:3.8', 'python:3.7']