version: 2.1

jobs:
  base_test:
    parameters:
      image:
        type: string
      test:
        type: string

    docker:
      - image: << parameters.image >>

    steps:
      - checkout
      - run: python --version
      - run: python runtest.py --verbose=3 -f .circleci/<< parameters.test >> -j 2 || if [[ $? == 2 ]]; then true; else false; fi

  tex_test:
    parameters:
      year:
        type: string
      python:
        type: string

    docker:
      - image: dmoody256/scons-texalive:texalive-<< parameters.year >>-python<< parameters.python >>

    steps:
      - checkout
      - run: python --version
      - run: python runtest.py --verbose=3 -f .circleci/tex_dockbook_test.txt -j 2 || if [[ $? == 2 ]]; then true; else false; fi

workflows:
  all_tests:
    jobs:
      - base_test:
          matrix:
            parameters:
              image: [
                'python:3.9',
                'python:3.8',
                'python:3.7',
                ]
              test: ['base_tests.txt']
      - tex_test:
          matrix:
            parameters:
              python: [
                '3.9',
                '3.8',
                '3.7',
                ]
              year: [
                '2019',
                '2018',
                '2017',
                ]