version: 2.1
jobs:
  build:
    docker:
      - image: 'python:3.8'
    steps:
      - run: python --version
      - checkout
      - run: python runtest.py -a -j 2 -v -s || if [[ $? == 2 ]]; then true; else false; fi

  build:
    docker:
      - image: 'python:3.7'
    steps:
      - run: python --version
      - checkout
      - run: python runtest.py -a -j 2 -v -s || if [[ $? == 2 ]]; then true; else false; fi